### ISSUE TITLE
Issue with `DFW_tract_centroids.shp` in Dallas-Fort Worth Case Study

### ISSUE THREAD

**Issue by ChengweiLou** [StanfordASL/pamod#25]
Hello Dr. Federico Rossi,

Firstly, I'd like to thank you for your work on the interaction between Autonomous Mobility-on-Demand systems and the power network. I found your paper and the associated codebase very insightful.

I encountered an issue while trying to run the Dallas-Fort Worth case study from the code repository associated with your paper. Here's a brief description:

**Environment**:
- Python Version: 3.11
- Installed packages: As per `requirements.txt`
- OS: Windows 10

**Steps to reproduce**:
1. Cloned the repository.
2. Installed all dependencies mentioned in `requirements.txt`.
3. Ran the Jupyter notebook `DFW_scenario_preparation`.
4. Encountered the following error when trying to open `DFW_tract_centroids.shp`:
```
DriverError: 'Data/road_network/DFW_tract_centroids/DFW_tract_centroids.shp' not recognized as a supported file format.
```

I'm reaching out to seek guidance on this. Is there a specific file format or library version I should be using to avoid this error? Or perhaps there's something I might have overlooked in the setup process?

Thank you in advance for your assistance and for sharing your work with the community.

Best Regards,
Chengwei

--- 

---------------------------------------------------------------------------CPLE_OpenFailedError                      Traceback (most recent call last)
File fiona\ogrext.pyx:136, in fiona.ogrext.gdal_open_vector()
File fiona\_err.pyx:291, in fiona._err.exc_wrap_pointer()CPLE_OpenFailedError: 'Data/road_network/DFW_tract_centroids/DFW_tract_centroids.shp' not recognized as a supported file format.

During handling of the above exception, another exception occurred:
DriverError                               Traceback (most recent call last)
Cell In[27], line 2      1 census_tracts = {}----> 2 with fiona.open(road_data_dir+'DFW_tract_centroids/DFW_tract_centroids.shp') as c:      3     for f in c:      4         tractid = f['properties']['GEO_ID']

File ~\AppData\Roaming\Python\Python311\site-packages\fiona\env.py:457, in ensure_env_with_credentials.<locals>.wrapper(*args, **kwds)    454     session = DummySession()    456 with env_ctor(session=session):--> 457     return f(*args, **kwds)
File ~\AppData\Roaming\Python\Python311\site-packages\fiona\__init__.py:308, in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, allow_unsupported_drivers, **kwargs)    305     path = parse_path(fp)    307 if mode in ("a", "r"):--> 308     colxn = Collection(    309         path,    310         mode,    311         driver=driver,    312         encoding=encoding,    313         layer=layer,    314         enabled_drivers=enabled_drivers,    315         allow_unsupported_drivers=allow_unsupported_drivers,    316         **kwargs    317     )    318 elif mode == "w":    319     colxn = Collection(    320         path,    321         mode,   (...)    330         **kwargs    331     )

File ~\AppData\Roaming\Python\Python311\site-packages\fiona\collection.py:243, in Collection.__init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, include_fields, wkt_version, allow_unsupported_drivers, **kwargs)    241 if self.mode == "r":    242     self.session = Session()--> 243     self.session.start(self, **kwargs)    244 elif self.mode in ("a", "w"):    245     self.session = WritingSession()

File fiona\ogrext.pyx:588, in fiona.ogrext.Session.start()

File fiona\ogrext.pyx:143, in fiona.ogrext.gdal_open_vector()

DriverError: 'Data/road_network/DFW_tract_centroids/DFW_tract_centroids.shp' not recognized as a supported file format

**Comment by federico3** [comment]
1. When you checked out the repo, were you able to download all files in `case_studies/Dallas_Fort-Worth/Data/road_network/DFW_tract_centroids`? I just tried to check out a fresh copy of the repo, and I encountered issues with the org's LFS quota being exhausted (@alvinsunyixiao @DanieleGammelli  or any of the org owners who come after you alphabetically, should we look into this? Also say hi to Marco from me! :) ). Note that, in order to be able to read the `.shp`, _all_ files with prefix `DFW_tract_centroids` in the folder should be downloaded. I am 95% sure this is the issue you are encountering.
1. Which version of Fiona are you using? I tried installing Fiona 1.8.11 on Python 3.11 but got some weird GDAL-related errors. I am able to import the files (or, the copy of the files on my hard drive, which according to Git is identical to the one committed to LFS that I cannot retrieve) with Fiona 1.8.11 on Python 3.8. Note that this work was done in 2017 on Python 3.6. I don't think this is the issue - I was able to open `DFW_tract_centroids.shp` with Fiona 1.9.4 on Python 3.11. But I am surprised that you were able to install the version of the packages pinned in `requirements.txt` on Python 3.11. If you encounter further issues, I recommend running an older version of Python, ideally 3.6.
1. If all else fails, you should be able to regenerate the `.shp` file from the instructions in the notebook, just above cell 11 where you read the file. I am copy-pasting that cell here for convenience.


> The centroids were  downloaded from USGS and centroids were computed in QGIS.
> 
> It's sometimes easier to go out-of-band, I think.
> 
> Here is how to recreate the file `DFW_tract_centroids.shp`:
> 
> - Download .shp shapefiles for census tracts. I believe the most recent copy may be found here:
https://catalog.data.gov/dataset/2019-cartographic-boundary-shapefile-current-census-tract-for-united-states-1-500000
> - Import the census tracts in QGIS and filter them to only keep census tracts in the DFW region. For that, you can right click on the layer in the Layers pane, select "Filter", and use this query:
> 
>    ```sql
>    "COUNTYFP" IN ('085','113','121','139','221','231','251','257','367','397','425','439','497') AND
>    "STATEFP" = '48'
>    ```
> 
>    (the county IDs are in the notebook above)
> At this point, you should see the census tracts for Dallas-Fort Worth.
> - Compute the centroids of the census tracts by calling `Vector->Geometry Tools->Centroids`. The centroids will appear as a new layer in QGIS.
> - Save the centroids layer: right-click on the layer in the Layers pane (bottom left), select `Export->Save Features As`, and select `ESRI Shapefile` as the output type. Save the layer as `DFW_tract_centroids.shp`. A copy of the file I generated is in the repo here:
>    https://github.com/StanfordASL/pamod/tree/master/case_studies/Dallas_Fort-Worth/Data/road_network/DFW_tract_centroids

EDIT: correction, this work was actually mostly done in Python 2.7! But I did convert the codebase to Python 3 and verify that everything ran with, I guess, 3.6 or 3.7, shortly before graduating

**Comment by federico3** [comment]
FWIW, here is my local copy of the files, in case the LFT issue is persistent. 
[DFW_tract_centroids.zip](https://github.com/StanfordASL/pamod/files/12841496/DFW_tract_centroids.zip)

Note that you can also probably just read in `DFW_tract_centroid_25cl_labels.csv` and skip the QGIS part, if you are OK with 25 centroids computed n years ago.

**Comment by ChengweiLou** [comment]
Hello Dr. Federico Rossi,

Thank you immensely for your prompt response.

1. I've made certain that I've downloaded all files located in `case_studies/Dallas_Fort-Worth/Data/road_network/DFW_tract_centroids`.
2. I'm running Python 3.11, and for Fiona's version, I initially attempted with the one listed in `requirements.txt`. However, I also later tried upgrading to Fiona's possibly latest version (around 1.9) but the issue with file reading persisted.
3. Concerning the installation of the package versions fixed in `requirements.txt` on Python 3.11 and the dependencies in `ubuntu_requirements.txt`, I did face challenges. Due to differences between Windows and Linux systems, the installation commands from GitHub seem to pose issues. For `requirements.txt`, it seems necessary to specify an absolute or relative path directly, while for `ubuntu_requirements.txt`, I might only have the option to directly install the corresponding dependencies on a Windows system.
4. In light of your suggestions, I'm contemplating downgrading my Python version and will  try to run the program on my local computer. 
5. As a preliminary step, I'll attempt with `DFW_tract_centroid_25cl_labels.csv` before venturing into the more intricate QGIS part.

Additionally, I'm toying with the idea of verifying the program in a smaller region, possibly adapting it to microgrids or distribution networks. Do you have any insights or advice in this regard? I greatly value your expertise and appreciate your willingness to share your thoughts.

Once again, thank you for your valuable input. It indeed aids my progress and learning.

Warm regards,
Chengwei Lou

**Comment by federico3** [comment]
> Additionally, I'm toying with the idea of verifying the program in a smaller region, possibly adapting it to microgrids or distribution networks. Do you have any insights or advice in this regard?

Re:trying with a smaller region, I would encourage that. As a first step, you could probably just adapt the clustering algorithm to a smaller region - census tracts are very small. One issue (that I believe you already hint at) is that, if the region you consider is too small, multiple clusters in the road network may end up connected to the same node in the transmission network, which makes the problem less interesting.

We did some work on including distribution networks; the problem we encountered is that, at the time, it was virtually impossible to get access to real models of distribution networks. We do have [a paper](https://arxiv.org/abs/1905.00200) where we used a synthetic model of a distribution network and sort of overlaid it on top of the road network - it wasn't super satisfactory, but it was the closest approximation of reality we were able to create. I recall that we reached out to multiple utilities both in the US and the UK, but they were unwilling to share plans.
